//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week14Friday.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Schedule
    {
        [Required]
        public int CRN { get; set; } 
        public string CourseNumber { get; set; }
        public string SectionNumber { get; set; }
        public string Days { get; set; }

        [StringLength(4)]
        public string StartTime { get; set; }
        public string EndTime { get; set; }

        //[DataType(DataType.EmailAddress)]
        //[StringLength(25, MinimumLength=1)]

    }
}
