//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week14Friday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int CRN { get; set; }
        public string CourseNumber { get; set; }
        public string SectionNumber { get; set; }
        public string Days { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }
}
